# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Daigou' do
pod "AFNetworking", "~> 2.6.0"
pod "FMDB", "~>2.5.0"
pod "ionicons", "~> 2.0.1"
pod "MJRefresh"
pod "Masonry","~> 0.5.3"
pod "JVFloatLabeledTextField"
pod "SDWebImage"
pod 'FXForms'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'FSImageViewer', '~> 2.6.3'
pod 'InAppSettingsKit', :git => 'git@github.com:futuretap/InAppSettingsKit.git'
end

target 'DaigouTests' do

end

